### PR TITLE
Remove procedures from picostdlib.nim

### PR DESCRIPTION
**Pull request by casey-SK**
I placed `sleep()` and `sleepMicroseconds` into the `time.nim` module and moved all of the other proc's inside `picostdlib` into `stdio.nim` . Personally, I prefer it this way, and believe it is more consistent across the board. 

I was not sure what effects deleting the `picostlib.nim` file would do to `nimble install` as a hybrid installation, so I didn't delete it yet.

### CODE REVIEW

**Comment by casey-SK** [comment]
I tested the following program, and it worked fine:

```nim
import picostdlib/[gpio, time, stdio]

stdioInitAll()

let led = 20.Gpio
led.init()
led.setDir(Out)
while true:
  led.put(High)
  sleep(1500)
  led.put(Low)
  print("blink")
  sleep(1500)

```

**Comment by beef331** [comment]
Bump the nimble version and update all examples.

**Comment by casey-SK** [comment]
would that mean you would just use
```nim
import picostdlib
```
and never have to worry about importing individual submodules?

**Comment by beef331** [comment]
Indeed, it'd export all sub modules making life easier if wanted.

**Comment by casey-SK** [comment]
do you think we want that, or do we want granular control? would there be a difference in size of the .uf2 file? I assume that Nim does not compile/import procs and modules which are never used?

**Comment by beef331** [comment]
It was just an idea. It does not compile code that's not needed, only code that's used.

**Comment by casey-SK** [comment]
I suppose to be idiomatic like the Nim standard library, we should just have one module imported?

**Comment by beef331** [comment]
I mean you can selectively import if needed, it's not really idiomatic, just an option.

**Comment by casey-SK** [comment]
okay. I don't mind import each submodule on it's own. So I guess we will leave it. If I try to delete the `picostdlib.nim` file however, I get the following error when I run `nimble install`:
```cmd
Error: Could not find a file with a .nimble extension inside the specified directory: /home/casey/Desktop/Learning/nim/pico-nim stdlib/picostdlib/docs
```

**Comment by casey-SK** [comment]
I remember running into this problem in another project. The solution is to leave it empty

**Comment by casey-SK** [comment]
I plan on making another PR very soon that will completely overhaul the examples folder. Can we have broken examples for a little bit and approve this PR?

**Comment by beef331** [comment]
Sounds fine for now, if you do not get the examples overhauled in due time I'll fix it myself.

**Comment by casey-SK** [comment]
sounds good!

**Pull request merged**
