### PR TITLE
add in time.nim -> timeUs32() and timeUs64() + example Hellotimestart.nim

### PR DESCRIPTION
**Pull request by Martinix75**

### CODE REVIEW

**Comment by beef331** [comment]
Can you rebase this please, there is only a single commit needed for this?

**Comment by beef331** [comment]
You did not rebase properly, you should only have a single commit in this PR.

**Comment by Martinix75** [comment]
add only 1 file for this commit

**Comment by Martinix75** [comment]
add example to use utime32()

**Comment by beef331** [comment]
My present issue with this PR is that you have 13 commits, this should be one commit, there is a lot of git history here which isnt needed. If you dont know how to properly rebase this I can suggest checking out the master of this repo, add the additions  then push to a new branch on your repo and make a new PR.

**Pull request closed without merging**
