### PR TITLE
Update picostdlib examples

### PR DESCRIPTION
**Pull request by casey-SK**
**Purpose:**

My intent here is to create a better structure for the *examples* included in the `picostdlib`. I have arranged the examples as follows: 

- Each example should be numbered, low numbers representing *easier / common* concepts and higher numbers representing *difficult / less common* concepts
- Each example should cover some basic functionality and try to limit itself to that functionality and concepts that have been covered already in the lower numbered examples.
- The examples should run on the original Pico, and require little in terms of external components. 
- The examples should include a title, description, and be well commented.

Note that so far, I have only completed 6 examples in the manor described, hope to finish the rest soon. I have tested them all to ensure that they run correctly.

I deleted the redundant examples that covered the same concepts, and left the examples the I have not yet look at. I also changed the import statements for the remaining hello_ programs.

I am curious to know how many examples you guys think we should have? did you have a limit in mind?

### CODE REVIEW

**Comment by beef331** [comment]
> I am curious to know how many examples you guys think we should have? did you have a limit in mind?
As many as you want, ideally these work as tests that the API atleast compiles and works, but the down side is hard to test.

**Comment by casey-SK** [comment]
haha, I haven't closed (#3) yet. I would like to at the very least test that they build without error. I watched a video about debugging, and it takes a lot of steps haha

**Comment by beef331** [comment]
Yea properly testing this stuff works is very much in the category of having a bunch of breakout boards that could be dropped on to test X module/feature.

**Comment by beef331** [comment]
For one the example PR should be separate to the examples. Though secondly i dont know how i feel with the solution for link libraries. Iterating every C file searching for a string seems ugh. Need to think about it more.

**Comment by casey-SK** [comment]
dang, sorry for being an amateur with git. I am going to close this PR and try again.

**Comment by beef331** [comment]
All you need to do is `git rebase -i HEAD~2` and drop the last commit(after making a nother branch), then push over this, then in the other branch drop everything but the latest commit doing `git rebase -i #commitBeforeWorkAdded` then dropping all between then and now.

**Comment by casey-SK** [comment]
Oh okay, once I try that, I will reopen this. Sorry for testing your patience like this haha

**Pull request closed without merging**
